### ISSUE TITLE
'NoneType' object has no attribute 'getEventContext'

### ISSUE THREAD

**Issue by will-moore** [ome/omero-web#383]
E.g when bsession and server are invalid numbers /webclient/?bsession=1234&server=1234'

```
Traceback (most recent call last):

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 538, in wrapped
    retval = f(request, *args, **kwargs)

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/decorators.py", line 597, in wrapper
    context = f(request, *args, **kwargs)

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webclient/views.py", line 576, in load_template
    return _load_template(request=request, menu=menu, conn=conn, url=url, **kwargs)

  File "/opt/omero/web/venv3/lib64/python3.6/site-packages/omeroweb/webclient/views.py", line 494, in _load_template
    active_group = request.session.get("active_group") or conn.getEventContext().groupId

AttributeError: 'NoneType' object has no attribute 'getEventContext'

<WSGIRequest: GET '/webclient/?bsession=1234&server=1234'>
```

Also seen on web upgrade when nginx might have cached old session IDs? 
https://www.openmicroscopy.org/qa2/qa/feedback/20540/

**Comment by gaelrayot-epfl** [comment]
Got the same error when upgrading from OMERO.Web 5.16 to 5.18 or 5.19

**Comment by gaelrayot-epfl** [comment]
May be related to https://github.com/ome/omero-web/issues/459
