### ISSUE TITLE
AttributeError: 'function' object has no attribute 'headers'

### ISSUE THREAD

**Issue by jburel** [ome/omero-web#494]
Error after upgrading to 5.22.0
```
Traceback (most recent call last):

File "/home/omero-web/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)

File "/home/omero-web/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/omero-web/.local/lib/python3.8/site-packages/omeroweb/feedback/views.py", line 102, in send_feedback
if is_ajax(request.is_ajax):

File "/home/omero-web/.local/lib/python3.8/site-packages/omeroweb/utils.py", line 38, in is_ajax
return request.headers.get("x-requested-with") == "XMLHttpRequest"

AttributeError: 'function' object has no attribute 'headers'
```

https://www.openmicroscopy.org/qa2/qa/feedback/33718/

**Comment by jburel** [comment]
cc @will-moore @knabar
