### PR TITLE
Remove left-over is_ajax property

### LINKED ISSUE #494: AttributeError: 'function' object has no attribute 'headers'
Error after upgrading to 5.22.0
```
Traceback (most recent call last):

File "/home/omero-web/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)

File "/home/omero-web/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/omero-web/.local/lib/python3.8/site-packages/omeroweb/feedback/views.py", line 102, in send_feedback
if is_ajax(request.is_ajax):

File "/home/omero-web/.local/lib/python3.8/site-packages/omeroweb/utils.py", line 38, in is_ajax
return request.headers.get("x-requested-with") == "XMLHttpRequest"

AttributeError: 'function' object has no attribute 'headers'
```

https://www.openmicroscopy.org/qa2/qa/feedback/33718/

### PR DESCRIPTION
**Pull request by knabar**
Fixes #494 

`is_ajax` property was accidentally left in https://github.com/ome/omero-web/commit/dfb1462cf30c2ea3f214c55ac55144035255d58f#diff-4858101b4bfcfaf6c55b0a41d15a313d5f9e5422aaa152a57acbe99450194b62L101

### CODE REVIEW

**Review by jburel — APPROVED** [review]

**Comment by jburel** [comment]
Propose to merge and tag as 5.22.1

**Review by chris-allan — APPROVED** [review]
